apiVersion: v1
kind: Service
metadata:
  name: {{ include "dynagent.fullname" . }}
  labels:
    {{- include "dynagent.labels" . | nindent 4 }}
  {{- if .Values.backendConfig.enabled }}
  annotations:
    cloud.google.com/backend-config: {{ printf "{\"default\": \"%s\"}" (.Values.backendConfig.name | default (include "dynagent.fullname" .)) | quote }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dynagent.selectorLabels" . | nindent 4 }}
